"""Added Activation Token Model

Revision ID: c77b7dbb793e
Revises: 419449619b80
Create Date: 2022-03-23 06:39:29.383919

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c77b7dbb793e'
down_revision = '419449619b80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activation_tokens',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('activation_code', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('expires_in', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_expired', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activation_tokens_activation_code'), 'activation_tokens', ['activation_code'], unique=False)
    op.create_index(op.f('ix_activation_tokens_email'), 'activation_tokens', ['email'], unique=False)
    op.create_index(op.f('ix_activation_tokens_id'), 'activation_tokens', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activation_tokens_id'), table_name='activation_tokens')
    op.drop_index(op.f('ix_activation_tokens_email'), table_name='activation_tokens')
    op.drop_index(op.f('ix_activation_tokens_activation_code'), table_name='activation_tokens')
    op.drop_table('activation_tokens')
    # ### end Alembic commands ###
