"""Fixed PasswordReset model name and email set to not unique

Revision ID: 419449619b80
Revises: fc492e3a613b
Create Date: 2022-03-22 20:09:50.335265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '419449619b80'
down_revision = 'fc492e3a613b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_password_resets_email', table_name='password_resets')
    op.create_index(op.f('ix_password_resets_email'), 'password_resets', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_password_resets_email'), table_name='password_resets')
    op.create_index('ix_password_resets_email', 'password_resets', ['email'], unique=False)
    # ### end Alembic commands ###
